### PR TITLE
Added workflow to automatically resize large gifs

### PR DESCRIPTION
**Pull request by SijmenHuizenga**
This pr adds a workflow that automatically resizes any gifs wider than 300px to 300px. This reasoning behind this procedure can be read in #62. It uses `imagick mogrify` which replaces the old file with the resized file. I noticed that sometimes a file has a larger filesize than after resize. I think this has something to do with compression. I don't think this is a problem since Imgbot will compress any uncompressed images anyway.

Relates to #62

## Pages/Interfaces that will change
Most images will be smaller. This should be an invisible change.

## Steps to test
[This example pr](https://github.com/SijmenHuizenga/httriri/pull/4) shows what happens when you add new images that are too large. It also shows that no commit is made if no files were changed.

### Additional notes
Why not just do `mogrify -resize '300>' public/images/*.gif` instead of looping? Because somehow running this resize command twice on the same file will change the file twice. Manually checking for width is more stable.

### CODE REVIEW

**Comment by M0nica** [comment]
This looks good to me. Thank you for contributing these optimizations! I am going to proceed with merging.

**Comment by M0nica** [comment]
Ah, actually it seems the current set up is having issues with fork and being able to push. https://github.com/actions/checkout/issues/124 

I am getting `fatal: You are not currently on a branch.` example: https://github.com/M0nica/httriri/runs/1217449782?check_suite_focus=true

This will need to be addressed before the action is runnable. I tried to make some hot fixes to the workflow but it looks like it will require a bit more work.

**Comment by SijmenHuizenga** [comment]
hmmm that's weird, on my fork it worked. I will investigate

**Comment by SijmenHuizenga** [comment]
I'm noting my investigation findings in #77

**Pull request merged**
