### PR TITLE
add 307 status code

### PR DESCRIPTION
**Pull request by chocho01**
Resole issue #38

### CODE REVIEW

**Comment by chocho01** [comment]
Resolve #51

**Comment by chocho01** [comment]
Resolve #38

**Comment by M0nica** [comment]
There are extra files updated in this PR. Can you update so that the only two files changed are the added image and the statuses.ts? Also, can you resolve the merge conflicts in `statuses.ts`?

**Comment by chocho01** [comment]
@M0nica sorry for the quick push, I haven't checked git index.... Should be fix

**Pull request merged**
