### PR TITLE
Add Rihanna gif for 504 Status code

### PR DESCRIPTION
**Pull request by mehtavishwa30**
# Description of Changes

Relates to #43
https://github.com/M0nica/httriri/issues/43

### CODE REVIEW

**Comment by M0nica** [comment]
Thank you for this contribution, the GIF you added for 504 currently is the same as the one for 403: Forbidden. Can you please update your PR as per the README "The GIF should include Rihanna and not already be included on https://www.httriri.com/. In rare cases, a GIF that already exists in the HTTRIRI collection can be used for another status code but within the same set of proposed changes a new GIF should be chosen for the other status code to ensure there are no duplicate images and the overall size of the collection is growing".

**Review by M0nica — CHANGES_REQUESTED** [review]
Please see my comment about the duplicate image.

**Comment by mehtavishwa30** [comment]
Thanks for the note! I'll make the changes asap.

**Comment by M0nica** [comment]
Closing this as the GIF is a duplicate. If you'd like to add a new image for 504 status code, if it hasn't been added yet that then you may./

**Pull request closed without merging**
