### PR TITLE
Add 205 status code

### PR DESCRIPTION
**Pull request by metalcamp**
# Description of Changes

Relates to #10 
https://github.com/M0nica/httriri/issues/10

## Pages/Interfaces that will change

- 205 status code

### CODE REVIEW

**Comment by M0nica** [comment]
@metalcamp this looks good to me. Are you able to resolve the merge conflicts either on the GitHub UI or command line? 

Here are some instructions on resolving merge conflicts in the GitHub UI: https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github

**Comment by metalcamp** [comment]
@M0nica updated.

**Comment by metalcamp** [comment]
@M0nica updated PR.

**Comment by M0nica** [comment]
Thank you for your contribution!

**Pull request merged**
