### PR TITLE
##Add Rihanna GIF for Status Code 599 #50

### PR DESCRIPTION
**Pull request by hulyak**
# 599: Network Connect Timeout Error

Relates to #

https://github.com/M0nica/httriri/issues/ #50

## Pages/Interfaces that will change

- public/images
- utils/statuses.ts

## Steps to test

I ran the project on localhost:3000

### CODE REVIEW

**Comment by M0nica** [comment]
@hulyak thank you for your contribution. The GIF you submitted is already in use for “406: Not Acceptable ↗”. Can you change the image? 

In the README it indicates:

> 
The GIF should include Rihanna and not already be included on https://www.httriri.com/. In rare cases, a GIF that already exists in the HTTRIRI collection can be used for another status code but within the same set of proposed changes a new GIF should be chosen for the other status code to ensure there are no duplicate images and the overall size of the collection is growing

**Comment by M0nica** [comment]
There’s currently another PR that was opened to add 599. https://github.com/M0nica/httriri/pull/57. If the requested changes are not made within 48 hours I will review PR 57.

**Comment by hulyak** [comment]
Hi, I have made a new pull request #75 with a different image.

**Comment by M0nica** [comment]
Closing as the new GIF for 599 was added in https://github.com/M0nica/httriri/pull/75

**Pull request closed without merging**
